GET http://localhost:8080/oauth/token?username=user_1&password=123456&grant_type=password&scope=select&client_id=client_2&client_secret=654321

###


GET http://localhost:8080/order/3
###
GET http://localhost:8080/product/3
### @EnableResourceServer,@EnableAuthorizationServer分离
GET http://localhost:8080/login
###
GET http://localhost:8080/login/test
###
